# integration tests for vite and svelte
name: integration-test

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      vite_ref:
        description: 'vite git ref'
        required: true
        default: 'main'
      vite_skip_verify:
        description: 'skip vite verification'
        required: true
        type: boolean
        default: false
      vite_plugin_svelte_ref:
        description: 'vite-plugin-svelte git ref'
        required: true
        default: 'main'
      vite_plugin_svelte_skip_verify:
        description: 'skip vite-plugin-svelte verification'
        required: true
        type: boolean
        default: false
      vite_plugin_svelte_skip_test:
        description: 'skip vite-plugin-svelte tests'
        required: true
        type: boolean
        default: false
      sveltekit_ref:
        description: 'sveltekit git ref'
        required: true
        default: 'master'
      sveltekit_skip_verify:
        description: 'skip sveltekit verification'
        required: true
        type: boolean
        default: false
jobs:
  integration-test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm@6
      - name: 'checkout vite'
        uses: actions/checkout@v2
        with:
          repository: 'vitejs/vite'
          ref: '${{github.event.inputs.vite_ref}}'
          path: 'vite'
      - name: 'install and build vite'
        working-directory: 'vite'
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci-build-vite
      - name: 'test vite'
        if: ${{!github.event.inputs.vite_skip_verify}}
        working-directory: 'vite'
        run: |
          pnpm run build-plugin-vue
          pnpm run build-plugin-react
          pnpm run test-serve -- --runInBand
          pnpm run test-build -- --runInBand
      - name: 'checkout vite-plugin-svelte'
        uses: actions/checkout@v2
        with:
          repository: 'sveltejs/vite-plugin-svelte'
          ref: '${{github.event.inputs.vite_plugin_svelte_ref}}'
          path: 'vite-plugin-svelte'
      - name: 'vite-plugin-svelte verification tests'
        if: ${{!github.event.inputs.vite_plugin_svelte_skip_verify}}
        working-directory: 'vite-plugin-svelte'
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm build:ci
          pnpm test:ci
      - name: 'link local vite to vite-plugin-svelte and build'
        working-directory: 'vite-plugin-svelte'
        run: |
          git clean -fdx
          mv package.json package.orig.json
          jq -r '.devDependencies.vite="${{github.workspace}}/vite/packages/vite"|.pnpm.overrides.vite="${{github.workspace}}/vite/packages/vite"' package.orig.json > package.json
          rm package.orig.json
          pnpm install --prefer-frozen-lockfile --prefer-offline
          pnpm build:ci
      - name: 'vite-plugin-svelte integration tests'
        if: ${{!github.event.inputs.vite_plugin_svelte_skip_test}}
        working-directory: 'vite-plugin-svelte'
        run: |
          pnpm test:ci
      - name: 'checkout sveltekit'
        uses: actions/checkout@v2
        with:
          repository: 'sveltejs/kit'
          ref: '${{github.event.inputs.sveltekit_ref}}'
          path: 'kit'
      - name: 'sveltekit verification tests'
        if: ${{!github.event.inputs.sveltekit_skip_verify}}
        working-directory: 'kit'
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          pnpm build --filter ./packages --filter !./packages/create-svelte/templates
          pnpm test
      - name: 'link local vite and vite-plugin-svelte to sveltekit and build'
        working-directory: 'kit'
        run: |
          git clean -fdx
          mv package.json package.orig.json
          jq -r '.devDependencies.vite="${{github.workspace}}/vite/packages/vite"|.pnpm.overrides.vite="${{github.workspace}}/vite/packages/vite"|.devDependencies."@sveltejs/vite-plugin-svelte"="${{github.workspace}}/vite-plugin-svelte/packages/vite-plugin-svelte"|.pnpm.overrides."@sveltejs/vite-plugin-svelte"="${{github.workspace}}/vite-plugin-svelte/packages/vite-plugin-svelte"' package.orig.json > package.json
          rm package.orig.json
          pnpm install --prefer-frozen-lockfile --prefer-offline
          pnpm build --filter ./packages --filter !./packages/create-svelte/templates
      - name: 'install, build and test sveltekit'
        working-directory: 'kit'
        run: |
          pnpm test
